### ISSUE TITLE
Unable to move a new "untracked file" toward a change list

### ISSUE THREAD

**Issue by thomaschampagne** [Aktyn/git-changelists-manager#2]
HI @Aktyn,

Thanks for continuing this extension extension! It's a must have from me. I used feature from jetbrain before.

I'm getting the following error, when I attempt to move a new "untracked file" toward a change list:

![image](https://github.com/Aktyn/git-changelists-manager/assets/151973/178e9171-dcac-488d-a22c-230f048dae76)

A fix on this is possible?

Thanks again for you help and your work,

Thomas

**Comment by Aktyn** [comment]
Hi @thomaschampagne 

The error comes from the git command `git update-index --assume-unchanged <path to file>`.
You cannot make git ignore files that are outside the git repository.

I can suggest putting the filename in a `.gitignore` file and optionally moving `.gitignore` itself to a changelist.

**Comment by thomaschampagne** [comment]
Hi @Aktyn,

Thanks for your quick reply and explanations. I think I understood the problem and the trick w/ .gitignore file 😄 

(I'm actually trying to perform a full switch from Jetbrain to VSCode where I was able to put untracked files in IDE changelists)

Thanks again for your time and work!

Regards,

Thomas
