### ISSUE TITLE
Add the ability to put uncommitted files to a changelist

### ISSUE THREAD

**Issue by nicolasbillamboz-arrive** [Aktyn/git-changelists-manager#3]
If I try to add an uncommited file to a change list I get this error:
```
Command failed: git update-index --assume-unchanged <my_file> fatal: Unable to mark file <my_file>
```
As a results the still appear in the default change list and not in the new one.

os ubuntu 20.04
vscode 1.93.0
aktyn.git-changelists-manager 1.0.2

**Comment by Aktyn** [comment]
Hello. This sounds similar to the problem described in #2 
Is the file you are trying to commit already a part of git repository but with uncommitted changes, or is it a new file?

**Comment by nicolasbillamboz-arrive** [comment]
This file is not part of the git repository, so yes it's the same case as the one reported in [#2](https://github.com/Aktyn/git-changelists-manager/issues/2). I understand the trick, but it is a workaround. If I add the file to the gitignore, I'm no longer able to see it in the default change list or in any other change lists, which is a bit disappointing, and not the output I expect. Is there any other way to achieve what I want: see untracked files in the new change list and not in the default one?

**Comment by Aktyn** [comment]
I can't think of any solution for that problem. This extension works by is based on git command that works only on tracked files.

**Comment by Aktyn** [comment]
I can't think of a solution to this problem. This extension relies on a git command that only works on tracked files.

I couldn't find any way to affect the contents of the _Changes_ list in _Source Control_, other than by running git commands.
![image](https://github.com/user-attachments/assets/c3043cb5-15b6-46f4-a7a1-eeb60aa1ee07)
This view is part of the `vscode.git` extension.
Simply put, there is currently no way to filter out or hide untracked files.

**Comment by Aktyn** [comment]
It is possible to **stash** an untracked file, but it will be removed from the disk, so I would rather not implement this behavior.

**Comment by GDXbsv** [comment]
Git: Smart Commit Changes

Set this setting to `tracked`

Your new files will not automatically be commited
